config/routes.rb
Rails.application.routes.draw do
  resources :sale_bills, except: [:destroy, :update]
  resources :concepts
  resources :account_employees, except: [:destroy]
  resources :budgets do
    member do
      get :cancel
      get :deliver
      get :reject
      get :get_detail
    end
  end
  #resources :budgets
  get 'rubros/search' => 'rubros#search'
  resources :rubros
  resources :certifications, except: [:destroy] do
    member do
      get :rejected
      get :approved
    end
  end
  resources :client_certifications do
    member do
      get :get_detail
    end
  end
  get 'employees/search' => 'employees#search'
  resources :employees
  resources :purchase_bills
  get 'providers/search' => 'providers#search'
  resources :providers
  get 'services/search' => 'services#search'
  resources :services
  get 'contracts/search' => 'contracts#search'
  resources :contracts
  get 'clients/search' => 'clients#search'
  resources :clients
  get 'materials/search' => 'materials#search'
  resources :materials
  resources :movement_details
  resources :material_movements
  resources :roles, except: [:destroy]
  resources :permissions, only: [:create, :update, :destroy]
  resources :audit, only: [:index]
  resources :installment_payment
  resources :installment_payment_purchase
  root to: 'welcome#index'
  get 'welcome/index'
  get 'profile', to: 'users#edit_profile', as: 'edit_profile'
  post 'profile', to: 'users#update_profile', as: 'update_profile'
  devise_for :users
  resources :users
  get 'company_config', to: 'company_config#edit_company', as: 'edit_company'
  post 'company_config', to: 'company_config#update_company', as: 'update_company'
  resources :budgets do
    resources :budgets_details
  end
  get 'reports' , to: 'reports#index', as: :reports
  get 'reports/materials' , to: 'reports#materials', as: :reports_materials
  get 'reports/bills' , to: 'reports#bills', as: :reports_bills
  get 'reports/employees' , to: 'reports#employees', as: :report_employees

end

app/models/employee.rb
class Employee < ApplicationRecord
  audited
  has_many :certifications
  has_many :account_employee_details

  validates :name,  :presence => {:message => "No puede estar en blanco"},
            :length => { maximum:30, :message => "Permite hasta 30 caracteres"},
            format: { :with => VALID_LETTER_REGEX, message: 'Solo permite letras'}

  validates :last_name,  :presence => {:message => "No puede estar en blanco"},
            :length => { maximum:30, :message => "Permite hasta 30 caracteres"},
            format: { :with => VALID_LETTER_REGEX, message: 'Solo permite letras'}

  validates :identification_document, :presence => {:message => "No puede estar en blanco"},
            :uniqueness => {:message => "Ya existe el numero de documento"}

  validates :email, format: { :with => VALID_EMAIL_REGEX , message: "El formato debe ser example@example.com" },
            :uniqueness => {:message => "El correo ya esta en uso, vuelva a intentarlo"},
            :allow_blank => true

  validates :phone, :uniqueness => {:message => "El numero ya existe"}, :allow_blank => true
  before_validation :rem_guion_to_ci

  def rem_guion_to_ci
    self.identification_document = identification_document.to_s.gsub(/\D/, '')
  end

  def name_with_initial
    "#{name} #{last_name}"
  end

end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  add_breadcrumb I18n.t('helpers.breadcrumbs.employees.index'), :employees_path

  before_action :set_employee, only: [:show, :edit, :update, :destroy]
  before_action :load_permissions
  authorize_resource

  def search
    @employees = Employee.where('name ILIKE ?', "%#{params[:q][:term]}%")
    render json: {items: @employees, total_count: @employees.count}
  end

  # GET /employees
  # GET /employees.json
  def index
    get_employees
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
    add_breadcrumb I18n.t('helpers.breadcrumbs.employees.show')
    @account_details = AccountEmployeeDetail.where(employee_id: @employee.id)
    @account = @employee.account_employee_details.page params[:page]
  end

  # GET /employees/new
  def new
    add_breadcrumb I18n.t('helpers.breadcrumbs.employees.new')
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
    add_breadcrumb I18n.t('helpers.breadcrumbs.employees.edit')
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to employees_path, notice: 'El empleado se creo correctamente.' }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to employees_path, notice: 'El empleado se edito correctamente.' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url, notice: 'El empleado se elimino correctamente.' }
      format.json { head :no_content }
    end
  end

  private
    def get_employees
      @q = Employee.ransack(params[:q])
      @q.sorts = ['name asc', 'last_name asc'] if @q.sorts.empty?
      @employees = @q.result.page(params[:page])
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_params
      params.require(:employee).permit(:name, :last_name, :address, :email, :phone, :identification_document, :balance)
    end
end

app/views/employees/_form.html.erb
<%= form_for employee, validate: true, :html => { class: 'form-horizontal' } do |f| %>
    <div class="box-body">
      <div class="field col-md-12 form-group">
        <div class="field col-md-6 form-group">
          <div class="col-md-2">
            <%= f.label :name, 'Nombre:', :class => 'control-label tooltip_required' %>
          </div>
          <div class="col-md-6">
            <%= f.text_field :name, :class => 'form-control', autofocus:true, :maxlength => 30 %>
          </div>
        </div>

        <div class="field col-md-6 form-group">
          <div class="col-md-2">
            <%= f.label :last_name, 'Apellido:', :class => 'control-label tooltip_required' %>
          </div>
          <div class="col-md-7">
            <%= f.text_field :last_name, :class => 'form-control', autofocus:true, :maxlength => 30 %>
          </div>
        </div>
      </div>

      <div class="field col-md-12 form-group">
        <div class="field col-md-6 form-group">
          <div class="col-md-2">
            <%= f.label :identification_document, 'CI:', :class => 'control-label tooltip_required' %>
          </div>
          <div class="col-md-5">
            <%= f.text_field :identification_document, id:'ci', :class => 'form-control' %>
          </div>
        </div>

        <div class="field col-md-6 form-group">
          <div class="col-md-2">
            <%= f.label :email, 'Correo:', :class => 'control-label' %>
          </div>
          <div class="col-md-6">
            <%= f.text_field :email, :class => 'form-control', :maxlength => 50 %>
          </div>
        </div>
      </div>

      <div class="field col-md-12 form-group">
        <div class="field col-md-6 form-group">
          <div class="col-md-2">
            <%= f.label :address, 'Direccion:', :class => 'control-label' %>
          </div>
          <div class="col-md-9">
            <%= f.text_area :address, :class => 'form-control', :maxlength => 150 %>
          </div>
        </div>

        <div class="field col-md-6 form-group">
          <div class="col-md-2">
            <%= f.label :phone, 'Telefono:', :class => 'control-label' %>
          </div>
          <div class="col-md-5">
            <%= f.text_field :phone, id: 'phone', :class => 'form-control', :maxlength => 12 %>
          </div>
        </div>
      </div>
    </div>

    <div class="box-footer clearfix">
      <div class="pull-right">
        <button type="submit" class="btn btn-primary" title="Guardar"><i class="fa fa-save"></i></button>
        <%= link_to "<i class=\"fa fa-arrow-left\"></i>".html_safe, employees_path, :class => 'btn btn-default', :title => 'Atrás' %>
      </div>
    </div>
<% end %>

app/views/employees/_list.html.erb
<table class="table table-bordered table-condensed table-list">
  <thead>
  <tr>
    <th>Nombre</th>
    <th>Apellido</th>
    <th>Documento</th>
    <th>Correo</th>
    <th>Dirección</th>
    <th>Teléfono</th>
    <th class="table-actions"></th>
  </tr>
  </thead>

  <tbody>
  <% employees.each do |employee| %>
      <tr>
        <td><%= employee.name %></td>
        <td><%= employee.last_name %></td>
        <td><%= employee.identification_document %></td>
        <td><%= employee.email %></td>
        <td><%= employee.address %></td>
        <td><%= employee.phone %></td>
        <td>
          <%= link_to "<i class=\"fa fa-eye\"></i>".html_safe, employee_path(employee), {:class => "btn btn-xs bg-teal", :title => "Ver"} %>
          <% if (can? :update, Employee) %>
              <%= link_to "<i class=\"fa fa-pencil\"></i>".html_safe, edit_employee_path(employee), {:class => "btn btn-xs bg-orange", :title => "Editar"} %>
          <% end %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/employees/edit.html.erb
<div class="box box-success">
  <div class="box-header with-border">
    <h3 class="box-title"><%= t('helpers.title.employee.edit') %></h3>
  </div>
  <%= render 'form', :employee => @employee %>
</div>

app/views/employees/index.html.erb
<div class="box box-success">
  <div class="box-header with-border box-success">
    <h3 class="box-title"><%= t('helpers.title.employee.list') %></h3>
    <% if (can? :create, Employee) %>
        <%= link_to "<i class=\"fa fa-plus\"></i>".html_safe, new_employee_path, {:class => "btn btn-sm bg-green btn-title", :title => "Agregar Empleado"} %>
    <% end %>
  </div>
  <div class="box-body">
    <div class="employee-search searchList">
      <%= search_form_for(@q, remote: true, :html => { class: 'remote-search' }) do |f| %>
          <div class="input-group">
            <%= f.text_field :name_or_last_name_or_identification_document_cont, class: 'form-control', autocomplete: 'off', placeholder: 'Busca por nombre, apellido o número de identificación' %>
            <div class="input-group-btn">
              <button type="submit" name="button" class="btn btn-default">
                <i class="fa fa-search"></i>
              </button>
            </div>
          </div>
      <% end %>
    </div>
    <div class="overlay-wrapper searchResult table-responsive" id="employees-table">
      <%= render 'list', :employees => @employees %>
    </div>
  </div>
  <div class="box-footer clearfix">
    <div id="paginate-container">
      <ul class="pagination pagination-sm no-margin pull-right">
        <%= paginate @employees %>
      </ul>
    </div>
  </div>
</div>

app/views/employees/index.js.slim
| $("#employees-table").html("#{escape_javascript(render 'list', format: 'html', :employees => @employees)}");
| $('#paginate-container').html("#{escape_javascript(paginate(@employees, remote: true)) }");
| $('.searchResult > .overlay').remove();

app/views/employees/new.html.erb
<div class="box box-success">
  <div class="box-header with-border">
    <h3 class="box-title"><%= t('helpers.title.employee.new') %></h3>
  </div>
  <%= render 'form', :employee => @employee %>
</div>

app/views/employees/show.html.erb
<div class="box box-success">
  <div class="box-header with-border">
    <h3 class="box-title"><%= t('helpers.title.employee.list') %></h3>
  </div>
  <div class="box-body">

    <div class="field col-md-12 form-group">
      <div class="field col-md-8 form-group">
        <strong>Nombre y Apellido:</strong>
        <%= @employee.name_with_initial%>
      </div>

      <div class="field col-md-4 form-group">
        <strong>Documento:</strong>
        <%= @employee.identification_document %>
      </div>
    </div>

    <div class="field col-md-12 form-group">
      <div class="field col-md-4 form-group">
        <strong>Correo:</strong>
        <%= @employee.email %>
      </div>

      <div class="field col-md-4 form-group">
        <strong>Dirección:</strong>
        <%= @employee.address %>
      </div>

      <div class="field col-md-4 form-group">
        <strong>Teléfono:</strong>
        <%= @employee.phone %>
      </div>
    </div>
  </div>
  <div class="box-footer">
    <div class="pull-right">
      <% if (can? :update, Employee) %>
          <%= link_to "<i class=\"fa fa-pencil\"></i>".html_safe, edit_employee_path(@employee), :class => 'btn bg-orange', :title => 'Ver' %>
      <% end %>
      <%= link_to "<i class=\"fa fa-arrow-left\"></i>".html_safe, employees_path, :class => 'btn btn-default', :title => 'Atrás' %>
    </div>
  </div>
</div>

<div class="box box-success">
  <div class="box-header with-border">
    <h3 class="box-title">Cuenta Corriente</h3>
  </div>
  <div class="box-body">
    <div class="field col-md-12 form-group">
      <div class="field col-md-8 form-group">
        <strong>Saldo Total:</strong>
        <%= number_to_currency(@employee.balance, unit: "Gs.", separator: ".", precision: 0) %>
      </div>
    </div>
    <div class="col-md-12">
      <table class="table table-bordered table-condensed", cellspacing="0" width="100%">
        <thead>
        <tr>
          <th>Contrato</th>
          <th>N° de certificación</th>
          <th>Monto Certificado</th>
          <th>Fecha de certificación</th>
          <th>Fecha de pago</th>
          <th>N° de recibo</th>
          <th>Estado del pago</th>
          <th width="5%"></th>
        </tr>
        </thead>
        <tbody>
            <% @account_details.each do |account| %>
                <tr>
                  <td><%= account.account_employee.contract_name%></td>
                  <td><%= account.certification.certification_number %>&nbsp;<%= link_to "<i class=\"fa fa-eye\"></i>".html_safe, certification_path(account.certification), :class => 'btn btn-xs bg-teal', :title => 'Ver Certificación' %></td>
                  <td><%= number_to_currency(account.total, unit: "Gs.", separator: ".", precision: 0) %></td>
                  <td><%= account.certification.date %></td>
                  <td><%= account.date %></td>
                  <td><%= account.number_bill %></td>
                  <td>
                    <% if account.state == "Pendiente" %>
                        <span class="label label-warning">Pendiente</span>
                    <% elsif account.state == "Pagado"%>
                        <span class="label label-default">Pagado</span>
                    <% end %>
                  </td>
                  <td>
                    <% if account.state == "Pendiente" %>
                        <%= link_to 'Generar Pago'.html_safe, edit_account_employee_path(account.account_employee_id), {:class => 'btn btn-xs btn-primary'} %>
                    <% end %>
                  </td>
                <tr>
            <% end %>
        </tbody>
      </table>
      <div id="paginate-container">
        <ul class="pagination pagination-sm no-margin pull-right">
          <%= paginate @account %>
        </ul>
      </div>
    </div>
  </div>
</div>