config/routes.rb
Rails.application.routes.draw do
  resources :sale_bills, except: [:destroy, :update]
  resources :concepts
  resources :account_employees, except: [:destroy]
  resources :budgets do
    member do
      get :cancel
      get :deliver
      get :reject
      get :get_detail
    end
  end
  #resources :budgets
  get 'rubros/search' => 'rubros#search'
  resources :rubros
  resources :certifications, except: [:destroy] do
    member do
      get :rejected
      get :approved
    end
  end
  resources :client_certifications do
    member do
      get :get_detail
    end
  end
  get 'employees/search' => 'employees#search'
  resources :employees
  resources :purchase_bills
  get 'providers/search' => 'providers#search'
  resources :providers
  get 'services/search' => 'services#search'
  resources :services
  get 'contracts/search' => 'contracts#search'
  resources :contracts
  get 'clients/search' => 'clients#search'
  resources :clients
  get 'materials/search' => 'materials#search'
  resources :materials
  resources :movement_details
  resources :material_movements
  resources :roles, except: [:destroy]
  resources :permissions, only: [:create, :update, :destroy]
  resources :audit, only: [:index]
  resources :installment_payment
  resources :installment_payment_purchase
  root to: 'welcome#index'
  get 'welcome/index'
  get 'profile', to: 'users#edit_profile', as: 'edit_profile'
  post 'profile', to: 'users#update_profile', as: 'update_profile'
  devise_for :users
  resources :users
  get 'company_config', to: 'company_config#edit_company', as: 'edit_company'
  post 'company_config', to: 'company_config#update_company', as: 'update_company'
  resources :budgets do
    resources :budgets_details
  end
  get 'reports' , to: 'reports#index', as: :reports
  get 'reports/materials' , to: 'reports#materials', as: :reports_materials
  get 'reports/bills' , to: 'reports#bills', as: :reports_bills
  get 'reports/employees' , to: 'reports#employees', as: :report_employees

end

app/models/rubro.rb
class Rubro < ApplicationRecord
  audited
  belongs_to :material
  belongs_to :service
  has_many :rubro_material_details
  has_many :rubro_service_details
  accepts_nested_attributes_for :rubro_material_details, allow_destroy: true
  accepts_nested_attributes_for :rubro_service_details, allow_destroy: true

  validates :name, :presence => {:message => "Debe ingresar un nombre"}

  validates :measurement_unit, :presence => {:message => "Debe ingresar una unidad de medida"}

  validates :utility, :presence => {:message => "Debe rellenar este campo"}

  validate :is_empty_details

  def final_price
    self.price * (1 + (self.utility/100))
  end
#end

  def is_empty_details
    if rubro_material_details.empty?
      errors.add(:measurement_unit, "Debe agregar al menos un material")
    end

    if rubro_service_details.empty?
      errors.add(:measurement_unit, "Debe agregar al menos un servicio")
    end
  end

end

app/controllers/rubros_controller.rb
class RubrosController < ApplicationController
  before_action :set_rubro, only: [:show, :edit, :update, :destroy]
  before_action :load_permissions
  authorize_resource
  add_breadcrumb I18n.t('helpers.breadcrumbs.rubros.index'), :rubros_path

  def search
    @rubros = Rubro.where('name ILIKE ?', "%#{params[:q][:term]}%")
    render json: {items: @rubros, total_count: @rubros.count}
  end
  # GET /rubros
  # GET /rubros.json
  def index
    get_rubros
  end

  # GET /rubros/1
  # GET /rubros/1.json
  def show
    add_breadcrumb I18n.t('helpers.breadcrumbs.rubros.show')
  end

  # GET /rubros/new
  def new
    add_breadcrumb I18n.t('helpers.breadcrumbs.rubros.new')
    @rubro = Rubro.new
    @rubro.utility = CompanyConfig.first.default_utility
    @rubro.rubro_material_details.build
    @rubro.rubro_service_details.build
  end

  # GET /rubros/1/edit
  def edit
    add_breadcrumb I18n.t('helpers.breadcrumbs.rubros.edit')
  end

  # POST /rubros
  # POST /rubros.json
  def create
    @rubro = Rubro.new(rubro_params)

    respond_to do |format|
      if @rubro.save
        format.html { redirect_to @rubro, notice: 'El rubro ha sido creado correctamente' }
        format.json { render :show, status: :created, location: @rubro }
      else
        format.html { render :new }
        format.json { render json: @rubro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rubros/1
  # PATCH/PUT /rubros/1.json
  def update
    respond_to do |format|
      if @rubro.update(rubro_params)
        format.html { redirect_to @rubro, notice: 'El rubro ha sido actualizado correctamente' }
        format.json { render :show, status: :ok, location: @rubro }
      else
        format.html { render :edit }
        format.json { render json: @rubro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rubros/1
  # DELETE /rubros/1.json
  def destroy
    @rubro.destroy
    respond_to do |format|
      format.html { redirect_to rubros_url, notice: 'El rubro ha sido eliminado correctamente.' }
      format.json { head :no_content }
    end
  end

  private
    def get_rubros
      @q = Rubro.ransack(params[:q])
      @q.sorts = ['name asc'] if @q.sorts.empty?
      @rubros = @q.result.page(params[:page])
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_rubro
      @rubro = Rubro.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rubro_params
      params.require(:rubro).permit(:name, :utility, :measurement_unit,
                                    :rubro_material_details_attributes => [:id, :material_id, :quantity, :price, :measurement_unit, :subtotal, :_destroy],
                                    :rubro_service_details_attributes => [:id, :service_id, :quantity, :price, :measurement_unit, :subtotal, :_destroy])
    end
end

app/views/rubros/_form.html.erb
<%= nested_form_for rubro, validate: true, :html => { class: 'form-horizontal' } do |f| %>
    <div class="box-body">
      <div class="field col-md-12 form-group">
        <div class="field col-md-6 form-group">
          <div class="col-md-3">
            <%= f.label :name, 'Nombre:', :class => 'control-label tooltip_required' %>
          </div>
          <div class="col-md-6">
            <%= f.text_field :name, :maxlength => 40, :class => 'form-control' %>
          </div>
        </div>

        <div class="field col-md-6 form-group">
          <div class="col-md-3">
            <%= f.label :utility, 'Utilidad:', :class => 'control-label tooltip_required' %>
          </div>
          <div class="col-md-6">
            <%= f.text_field :utility, :class => 'form-control maskPercentage' %>
          </div>
        </div>
      </div>

      <div class="field col-md-12 form-group">
        <div class="field col-md-6 form-group">
          <div class="col-md-3">
            <%= f.label :measurement_unit, 'Ud. medida:', :class => 'control-label tooltip_required' %>
          </div>
          <div class="col-md-6">
            <%= f.text_field :measurement_unit, :maxlength => 35, :class => 'form-control' %>
          </div>
        </div>
      </div>

      <div class="col-md-10">
        <div class="box box-success">
          <div class="box-header with-border">
            <h3 class="box-title">Materiales</h3>
          </div>
          <div class="box-body">
            <table class="table table-bordered" id="material-table">
              <tr>
                <th class="col-md-3">Material</th>
                <th class="col-md-2">Cantidad</th>
                <th class="col-md-1">Unidad</th>
                <th class="col-md-2">Precio</th>
                <th class="col-md-2">Subtotal</th>
                <th class="col-md-1"></th>
              </tr>
              <tbody id="material-details-body">
              <%= f.fields_for :rubro_material_details, :wrapper => false do |form| %>
                   <tr class="fields">
                    <td class="col-md-3"><%=form.collection_select(:material_id, Material.all, :id, :name, {prompt: 'Seleccionar'}, class: 'form-control select2 material-search')%></td>
                     <td class="col-md-2"><%=form.text_field :quantity, class: 'form-control qty text-right'%></td>
                     <td class="col-md-2"><%=form.text_field :measurement_unit, class: 'form-control measurement text-right', readonly: true%></td>
                     <td class="col-md-2"><%=form.text_field :price, class: 'form-control maskMoneda unit-price text-right', readonly: true%></td>
                     <td class="subtotal text-right"><%= form.object.subtotal ? number_to_currency(form.object.subtotal, unit: '') : 0 %></td>
                    <td class="col-md-1"><%=form.link_to_remove '<i class="fa  fa-trash-o"></i>'.html_safe, class: 'btn btn-sm btn-danger', title:'Eliminar'%></td>
                  </tr>
              <% end %>
              <tr>
                <td><%=f.link_to_add '<i class="fa fa-plus"></i>'.html_safe, :rubro_material_details, class: 'btn btn-sm btn-success insert_in_table', title:'Agregar'%></td>
              </tr>
              </tbody>
            </table>
          </div>

        </div>
      </div>

      <div class="col-md-10">
        <div class="box box-success">
          <div class="box-header with-border">
            <h3 class="box-title">Servicios</h3>
          </div>
          <div class="box-body">
            <table class="table table-bordered" id="service-table">
              <tr>
                <th class="col-md-3">Servicio</th>
                <th class="col-md-2">Cantidad</th>
                <th class="col-md-2">Unidad</th>
                <th class="col-md-2">Precio</th>
                <th class="col-md-2">Subtotal</th>
                <th class="col-md-1"></th>
              </tr>
              <tbody id="service-details-body">
              <%= f.fields_for :rubro_service_details, :wrapper => false do |form| %>
                  <tr class="fields">
                    <td class="col-md-3"><%=form.collection_select(:service_id, Service.all, :id, :name, {prompt: 'Seleccionar'}, class: 'form-control select2 service-search')%></td>
                    <td class="col-md-2"><%=form.text_field :quantity, class: 'form-control qty text-right'%></td>
                    <td class="col-md-2"><%=form.text_field :measurement_unit, class: 'form-control measurement text-right', readonly: true%></td>
                    <td class="col-md-2"><%=form.text_field :price, class: 'form-control maskMoneda unit-price text-right', readonly: true%></td>
                    <td class="subtotal text-right"><%= form.object.subtotal ? number_to_currency(form.object.subtotal, unit: '') : 0 %></td>
                    <td class="col-md-1"><%=form.link_to_remove '<i class="fa  fa-trash-o"></i>'.html_safe, class: 'btn btn-sm btn-danger', title:'Eliminar'%></td>
                  </tr>
              <% end %>
              <tr>
                <td><%=f.link_to_add '<i class="fa fa-plus"></i>'.html_safe, :rubro_service_details, class: 'btn btn-sm btn-success insert_in_table', title:'Agregar'%></td>
              </tr>
              </tbody>
            </table>
          </div>

        </div>
      </div>
    </div>

    <div class="box-footer">
      <div class="pull-right">
        <% if controller.action_name == 'edit'  %>
            <button type="submit" class="btn btn-primary" title="Guardar"><i class="fa fa-save"></i></button>
        <% else %>
            <button type="submit" class="btn btn-primary" title="Guardar"><i class="fa fa-save"></i></button>
        <% end %>
        <%= link_to "<i class=\"fa fa-arrow-left\"></i>".html_safe,  rubros_path , class: 'btn btn-default', title:'Atrás' %>
      </div>
    </div>
<% end %>

<script type="text/javascript">
  Rubro.setSearchMaterial('<%= materials_search_path %>');
  Rubro.setSearchService('<%= services_search_path %>');
</script>

app/views/rubros/_list.erb
<table class="table table-bordered table-condensed table-list">
  <thead>
  <tr>
    <th>Nombre</th>
    <th>Unidad</th>
    <th>Utilidad</th>
    <th>Precio</th>
    <th class="table-actions"></th>
  </tr>
  </thead>

  <tbody>
  <% rubros.each do |rubro| %>
      <tr>
        <td><%= rubro.name %></td>
        <td><%= rubro.measurement_unit %></td>
        <td><%= number_to_percentage(rubro.utility, precision: 2) %></td>
        <td><%= number_to_currency_py(rubro.final_price.to_i) %></td>
        <td>
          <%= link_to "<i class=\"fa fa-eye\"></i>".html_safe, rubro_path(rubro), {:class => "btn btn-xs bg-teal", :title => "Ver"} %>
          <% if (can? :update, Rubro) %>
          <%= link_to "<i class=\"fa fa-pencil\"></i>".html_safe, edit_rubro_path(rubro), {:class => "btn btn-xs bg-orange", :title => "Editar"} %>
              <% end %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/rubros/edit.html.erb
<div class="box box-success">
  <div class="box-header with-border">
    <h3 class="box-title"><%= "Editar Rubro" %></h3>
  </div>
  <%= render 'form', :rubro => @rubro %>
</div>

app/views/rubros/index.html.erb
<div class="box box-success">
  <div class="box-header with-border box-success">
    <h3 class="box-title">Rubros</h3>
    <% if (can? :create, Rubro) %>
        <%= link_to "<i class=\"fa fa-plus\"></i>".html_safe, new_rubro_path, {:class => "btn btn-sm bg-green btn-title", :title => "Agregar"} %>
    <% end %>
  </div>
  <div class="box-body">
    <div class="rubro-search searchList">
      <%= search_form_for(@q, remote: true, :html => { class: 'remote-search' }) do |f| %>
          <div class="input-group">
            <%= f.text_field :name_cont, class: 'form-control', autocomplete: 'off', placeholder: 'Busca por nombre' %>
            <div class="input-group-btn">
              <button type="submit" name="button" class="btn btn-default">
                <i class="fa fa-search"></i>
              </button>
            </div>
          </div>
      <% end %>
    </div>
    <div class="overlay-wrapper searchResult table-responsive" id="rubros-table">
      <%= render 'list', :rubros => @rubros %>
    </div>
  </div>
  <div class="box-footer clearfix">
    <div id="paginate-container">
      <ul class="pagination pagination-sm no-margin pull-right">
        <%= paginate @rubros %>
      </ul>
    </div>
  </div>
</div>

app/views/rubros/index.js.slim
| $("#rubros-table").html("#{escape_javascript(render 'list', format: 'html', :rubros => @rubros)}");
| $('#paginate-container').html("#{escape_javascript(paginate(@rubros, remote: true)) }");
| $('.searchResult > .overlay').remove();

app/views/rubros/new.html.erb
<div class="box box-success">
  <div class="box-header with-border">
    <h3 class="box-title"><%= "Agregar Rubro" %></h3>
  </div>
  <%= render 'form', :rubro => @rubro %>
</div>

app/views/rubros/show.html.erb
<div class="box box-success">
  <div class="box-header with-border">
    <h3 class="box-title"><%= "Rubro" %></h3>
  </div>
  <div class="box-body">
    <div class="col-md-12 form-group">
      <div class="col-sm-3 show-padding">
        <strong>Nombre:</strong>
        <%= @rubro.name %>
      </div>
      <div class="col-sm-3 show-padding">
        <strong>Unidad de medida:</strong>
        <%= @rubro.measurement_unit %>
      </div>
      <div class="col-sm-3 show-padding">
        <strong>Utilidad:</strong>
        <%= number_to_percentage(@rubro.utility, precision: 2) %>
      </div>
      <div class="col-sm-3 show-padding">
        <strong>Precio:</strong>
        <%= number_to_currency_py(@rubro.final_price.to_i) %>
      </div>
    </div>

    <div class="col-md-10 form-group">
        <table class="table table-bordered table-condensed table-list" style="margin-top: 50px; border-top: 3px solid green">
          <thead>
          <tr>
            <th>Material</th>
            <th>Cantidad</th>
            <th>Unidad</th>
            <th>Precio Unitario</th>
            <th>Subtotal</th>
          </tr>
          </thead>
          <tbody>
          <% @rubro.rubro_material_details.each do |detalle| %>
              <tr>
                <td><%= detalle.material.name %></td>
                <td class="text-right"><%= number_with_precision(detalle.quantity, precision: 2) %></td>
                <td class="text-right"><%= detalle.material.measurement_unit %></td>
                <td class="text-right"><%= number_to_currency_py(detalle.material.price) %></td>
                <td class="text-right"><%= number_to_currency_py(detalle.subtotal) %></td>
              </tr>
          <% end %>
          </tbody>
          <tfoot>
            <tr>
              <td colspan="4" class="text-bold text-right">Total:</td>
              <td class="text-bold text-right"><%= number_to_currency_py(@rubro.rubro_material_details.sum(:subtotal)) %></td>
            </tr>
          </tfoot>
        </table>


        <table class="table table-bordered table-condensed table-list" style="margin-top: 50px; border-top: 3px solid green">
          <thead>
          <tr>
            <th>Servicio</th>
            <th>Cantidad</th>
            <th>Unidad</th>
            <th>Precio Unitario</th>
            <th>Subtotal</th>
          </tr>
          </thead>
          <tbody>
          <% @rubro.rubro_service_details.each do |detalle| %>
              <tr>
                <td><%= detalle.service.name %></td>
                <td class="text-right"><%= number_with_precision(detalle.quantity, precision: 2) %></td>
                <td class="text-right"><%= detalle.service.measurement_unit %></td>
                <td class="text-right"><%= number_to_currency_py(detalle.service.price) %></td>
                <td class="text-right"><%= number_to_currency_py(detalle.subtotal) %></td>
              </tr>
          <% end %>
          </tbody>
          <tfoot>
          <tr>
            <td colspan="4" class="text-bold text-right">Total:</td>
            <td class="text-bold text-right"><%= number_to_currency_py(@rubro.rubro_service_details.sum(:subtotal)) %></td>
          </tr>
          </tfoot>
        </table>
    </div>

  </div>
  <div class="box-footer">
    <div class="pull-right">
      <% if (can? :update, Rubro) %>
          <%= link_to "<i class=\"fa fa-pencil\"></i>".html_safe, edit_rubro_path(@rubro), {:class => "btn  bg-orange", :title => "Editar"} %>
      <% end %>
      <%= link_to "<i class=\"fa fa-arrow-left\"></i>".html_safe, url_for(:back), {:class => "btn btn-default", :title => "Atrás"} %>
    </div>
  </div>
</div>