config/routes.rb
Rails.application.routes.draw do
  resources :sale_bills, except: [:destroy, :update]
  resources :concepts
  resources :account_employees, except: [:destroy]
  resources :budgets do
    member do
      get :cancel
      get :deliver
      get :reject
      get :get_detail
    end
  end
  #resources :budgets
  get 'rubros/search' => 'rubros#search'
  resources :rubros
  resources :certifications, except: [:destroy] do
    member do
      get :rejected
      get :approved
    end
  end
  resources :client_certifications do
    member do
      get :get_detail
    end
  end
  get 'employees/search' => 'employees#search'
  resources :employees
  resources :purchase_bills
  get 'providers/search' => 'providers#search'
  resources :providers
  get 'services/search' => 'services#search'
  resources :services
  get 'contracts/search' => 'contracts#search'
  resources :contracts
  get 'clients/search' => 'clients#search'
  resources :clients
  get 'materials/search' => 'materials#search'
  resources :materials
  resources :movement_details
  resources :material_movements
  resources :roles, except: [:destroy]
  resources :permissions, only: [:create, :update, :destroy]
  resources :audit, only: [:index]
  resources :installment_payment
  resources :installment_payment_purchase
  root to: 'welcome#index'
  get 'welcome/index'
  get 'profile', to: 'users#edit_profile', as: 'edit_profile'
  post 'profile', to: 'users#update_profile', as: 'update_profile'
  devise_for :users
  resources :users
  get 'company_config', to: 'company_config#edit_company', as: 'edit_company'
  post 'company_config', to: 'company_config#update_company', as: 'update_company'
  resources :budgets do
    resources :budgets_details
  end
  get 'reports' , to: 'reports#index', as: :reports
  get 'reports/materials' , to: 'reports#materials', as: :reports_materials
  get 'reports/bills' , to: 'reports#bills', as: :reports_bills
  get 'reports/employees' , to: 'reports#employees', as: :report_employees

end

app/models/purchase_bill.rb
class PurchaseBill < ApplicationRecord
  extend Enumerize
  audited
  belongs_to :provider
  delegate :name, :ruc, to: :provider, prefix: true

  has_many :purchase_details
  has_many :payments
  has_many :installment_purchases
  accepts_nested_attributes_for :installment_purchases

  enumerize :condition, in: [:contado, :crédito], predicates: true
  enumerize :state, in: [:pendiente, :pagado], predicates: true

  #after_validation :set_total
  after_validation :set_balance, if: :crédito?
  after_validation :set_state
  after_save :set_payment, if: :contado?

  accepts_nested_attributes_for :purchase_details, allow_destroy: true

  validates :condition, :presence => {:message => "Debe seleccionar una condicion de pago"}

  validates :number, :presence => {:message => "Debe rellenar este campo"}

  validates :date, :presence => {:message => "No puede estar en blanco"}

  validates :provider_id, :presence => {:message => "Debe seleccionar un proveedor"}



  #def set_total
  #  self.total = 0
  #  self.purchase_details.each do |d|
  #    self.total += d.price * d.quantity unless d.marked_for_destruction?
  #  end
  #end

  def set_state
    if self.balance == 0
      self.state = :pagado
    else
      self.state = :pendiente
    end
  end

  def set_balance
    self.balance = self.total
  end

  def set_payment
    payment = Payment.new
    payment.date = Time.zone.now
    payment.amount = self.total
    payment.balance = 0
    payment.purchase_bill_id = self.id
    payment.save()
  end

end

app/controllers/purchase_bills_controller.rb
class PurchaseBillsController < ApplicationController
  add_breadcrumb I18n.t('helpers.breadcrumbs.purchase_bills.index'), :purchase_bills_path

  before_action :set_purchase_bill, only: [:show, :edit, :update, :destroy]
  before_action :load_permissions
  authorize_resource

  def index
    get_purchases
  end

  def show
    add_breadcrumb I18n.t('helpers.breadcrumbs.purchase_bills.show', purchase: @purchase_bill.number)
  end

  def new
    add_breadcrumb I18n.t('helpers.breadcrumbs.purchase_bills.new')
    @purchase_bill = PurchaseBill.new
    @purchase_bill.date = Time.now
    @purchase_bill.purchase_details.build
  end

  def edit
    add_breadcrumb I18n.t('helpers.breadcrumbs.purchase_bills.edit')
  end

  def create
    add_breadcrumb I18n.t('helpers.breadcrumbs.purchase_bills.new')
    @purchase_bill = PurchaseBill.new(purchase_bill_params)
    if total_cuotas != @purchase_bill.total && @purchase_bill.condition.crédito?
      flash[:alert] = 'La suma de las cuotas deben ser igual al monto total de la factura.'
      render 'new'
    else
      if @purchase_bill.save
        redirect_to purchase_bills_path, notice: 'La factura de compra ha sido creada correctamente.'
      else
        render 'new'
      end
    end
  end

  def update
    add_breadcrumb I18n.t('helpers.breadcrumbs.purchase_bills.edit')
    @purchase_bill = PurchaseBill.find(params[:id])
    if @purchase_bill.update(purchase_bill_params)
      redirect_to purchase_bills_path, :notice => "La factura se edito correctamente."
    else
      render :edit
    end
  end


  def destroy
    @purchase_bill.destroy
    respond_to do |format|
      format.html { redirect_to purchase_bills_url, notice: 'Purchase bill was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def get_purchases
      @q = PurchaseBill.ransack(params[:q])
      @q.sorts = ['date desc'] if @q.sorts.empty?
      @purchase_bills = @q.result.page(params[:page])
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_purchase_bill
      @purchase_bill = PurchaseBill.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def purchase_bill_params
      params.require(:purchase_bill).permit(:date, :condition, :number, :total, :balance, :provider_id,
                                            :purchase_details_attributes => [:id, :quantity, :material_id, :price, :total, :_destroy],
                                            :installment_purchases_attributes => [:id, :amount, :balance, :due_date, :_destroy])
    end

    def total_cuotas
      total = 0
      @purchase_bill.installment_purchases.each do |i|
        total += (i.amount ? i.amount : 0)
      end
      return total
    end
end

app/views/purchase_bills/_details_table.html.erb
<table class="table table-bordered" id="purchase-table">
  <thead>
    <tr>
      <th class="col-md-4">Material</th>
      <th>Unidad</th>
      <th>Cantidad</th>
      <th>Precio Unitario</th>
      <th>Subtotal</th>
      <th class="table-actions"></th>
    </tr>
  </thead>
  <tbody id="details-body">
    <%= f.fields_for :purchase_details, :wrapper => false do |form| %>
      <tr class="fields">
        <td class="col-md-4">
          <%= form.collection_select :material_id, Material.all, :id, :name, {prompt: 'Buscar Material'}, {class: "form-control select2 material-search"} %>
        </td>
        <td><input class="form-control measurement text-right" value="<%=form.object.material.nil? ? '' : form.object.material.measurement_unit %>" readonly></td>
        <td><%=form.text_field :quantity, class: 'form-control qty text-right'%></td>
        <td><%=form.text_field :price, class: 'form-control maskMoneda unit-price text-right'%></td>
        <td class="subtotal text-right"><%= form.object.total ? form.object.total : 0 %></td>
        <td><%=form.link_to_remove '<i class="fa fa-trash-o"></i>'.html_safe, class: 'btn btn-sm bg-red', title: 'Eliminar material'%></td>
      </tr>
    <% end %>
    <tr>
      <td colspan="3">
        <%= f.link_to_add '<i class="fa fa-plus"></i>'.html_safe, :purchase_details, class: 'btn btn-sm bg-green insert_in_table', title: 'Agregar material' %>
      </td>
      <td class="text-right text-bold">Total:</td>
      <td class="text-right">Gs. <span class="table-total"><%= purchase_bill.total ? purchase_bill.total : 0 %></span>
        <%= f.hidden_field :total, :class => 'maskMonedaa form-control input_total' %>
      </td>
      <td></td>
    </tr>
  </tbody>
</table>

app/views/purchase_bills/_form.html.erb
<%= nested_form_for purchase_bill, validate: true, :html => { class: 'form-horizontal' } do |f| %>
  <div class="box-body">
    <div class="row">
      <div class="col-md-12">
        <div class="col-md-8">
          <div class="field col-md-6 form-group">
            <div class="col-md-3">
              <%= f.label :date, 'Fecha:', :class => 'control-label  tooltip_required' %>
            </div>
            <div class="col-md-7">
              <div class="input-group">
                <%= f.text_field :date, :class => 'form-control datepicker' %>
                <div class="input-group-addon"><i class="fa fa-calendar"></i></div>
              </div>
            </div>
          </div>
          <div class="field col-md-6 form-group">
            <div class="col-md-3">
              <%= f.label :provider, 'Proveedor:', :class => 'control-label  tooltip_required' %>
            </div>
            <div class="col-md-7">
              <div class="input-group">
                <%= f.collection_select(:provider_id, Provider.all, :id, :name, {prompt: 'Buscar Proveedor'}, :class => 'form-control select2 people-search') %>
                <span class="input-group-btn">
                  <%= link_to "<i class=\"fa fa-plus\"></i>".html_safe, new_provider_path, {:class => "btn btn-flat bg-green", :title => "Agregar Proveedor"} %>
                </span>
              </div>
            </div>
          </div>
          <div class="field col-md-6 form-group">
            <div class="col-md-4">
              <%= f.label :number, 'N° de boleta:', :class => 'control-label tooltip_required' %>
            </div>
            <div class="col-md-6">
              <%= f.text_field :number, :id => 'bill', :class => 'form-control' %>
            </div>
          </div>
          <div class="field col-md-6 form-group">
            <div class="col-md-3">
              <%= f.label :condition, 'Condición:', :class => 'control-label tooltip_required' %>
            </div>
            <div class="col-md-7">
              <div class="btn-group" data-toggle="buttons">
                <label class="btn btn-default">
                  <%= f.radio_button :condition, 'contado', :class => 'radio_group_buttons required condition' %> Contado
                </label>
                <label class="btn btn-default">
                  <%= f.radio_button :condition, 'crédito', :class => 'radio_group_buttons required condition' %> Crédito
                </label>
              </div>
            </div>
          </div>
        </div>
        <div class="col-md-4">
          <div class="panel-group accordion" id="accordion" style="display: none;">
            <div class="panel panel-default">
              <div class="panel-heading">
                <h4 class="panel-title">
                  <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne">Establecer Cuotas</a>
                </h4>
              </div>
              <div id="collapseOne" class="panel-collapse collapse in">
                <table class="table table-bordered table-condensed" id="">
                  <thead>
                    <tr>
                      <th class="col-md-6">Fecha de vencimiento</th>
                      <th class="col-md-5">Monto</th>
                      <th class="col-md-1"></th>
                    </tr>
                  </thead>
                  <tbody id="details-body-cuota">
                    <%= f.fields_for :installment_purchases, :wrapper => false do |form| %>
                      <tr class="fields">
                        <td class="col-md-6"><%=form.text_field :due_date, :class => 'form-control datepicker input-sm' %></td>
                        <td class="col-md-5"><%=form.text_field :amount, class: 'form-control maskMoneda text-right input-sm', :maxlength => 19%></td>
                        <td class="col-md-1"><%=form.link_to_remove '<i class="fa fa-trash-o"></i>'.html_safe, class: 'btn bg-red btn-sm', title: 'Eliminar material'%></td>
                      </tr>
                    <% end %>
                    <tr>
                      <td colspan="3">
                        <%= f.link_to_add '<i class="fa fa-plus"></i>'.html_safe.html_safe, :installment_purchases, class: 'btn bg-green btn-sm insert_in_table', title: 'Agregar Cuota' %>
                      </td>
                    </tr>
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        <div class="box box-success">
          <div class="box-header with-border">
            <h3 class="box-title">Seleccionar Materiales</h3>
          </div>
          <div class="box-body">
            <%= render 'details_table', :f => f, :purchase_bill => purchase_bill%>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="box-footer clearfix">
    <div class="pull-right">
      <button type="submit" class="btn btn-primary" title="Guardar"><i class="fa fa-save"></i></button>
      <%= link_to "<i class=\"fa fa-arrow-left\"></i>".html_safe,  purchase_bills_path , class: 'btn btn-flat btn-default', title: 'Atrás' %>
    </div>
  </div>
<% end %>

<script type="text/javascript">
  Purchase.setSearchProvider('<%= providers_search_path %>');
  Purchase.setSearchMaterial('<%= materials_search_path %>');
</script>

app/views/purchase_bills/_list.erb
<table class="table table-bordered table-condensed">
  <thead>
  <tr>
    <th>Fecha</th>
    <th>Proveedor</th>
    <th>Condicion</th>
    <th>Numero</th>
    <th class="table-actions"></th>
  </tr>
  </thead>

  <tbody>
  <% purchase_bills.each do |purchase_bill| %>
      <tr>
        <td><%= purchase_bill.date.strftime("%d/%m/%Y") %></td>
        <td><%= purchase_bill.provider_name %></td>
        <td><%= purchase_bill.condition %></td>
        <td><%= purchase_bill.number %></td>

        <td>
          <%= link_to "<i class=\"fa fa-eye\"></i>".html_safe, purchase_bill_path(purchase_bill), {:class => "btn btn-xs bg-teal btn-flat"} %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/purchase_bills/_list.html.erb
<table class="table table-bordered table-condensed table-list">
  <thead>
  <tr>
    <th>Fecha</th>
    <th>Nro. Factura</th>
    <th>Proveedor</th>
    <th>Condicion</th>
    <th>Monto</th>
    <th>Estado</th>
    <th class="table-actions"></th>
  </tr>
  </thead>

  <tbody>
  <% purchase_bills.each do |purchase_bill| %>
      <tr>
        <td><%= purchase_bill.date.strftime("%d/%m/%Y") %></td>
        <td><%= purchase_bill.number %></td>
        <td><%= purchase_bill.provider_name %></td>
        <td><%= purchase_bill.condition %></td>
        <td><%= number_to_currency_py(purchase_bill.total) %></td>
        <td>
          <%= "<label class='label label-#{purchase_bill.state.pagado? ? 'success' : 'warning'}'>#{purchase_bill.state_text}</label>".html_safe %>
        </td>
        <td>
          <%= link_to "<i class=\"fa fa-eye\"></i>".html_safe, purchase_bill_path(purchase_bill), {:class => "btn btn-xs bg-teal", :title => "Ver detalles"} %>
          <!--<% if (can? :update, PurchaseBill) %>
              <%= link_to "<i class=\"fa fa-pencil\"></i>".html_safe, edit_purchase_bill_path(purchase_bill), {:class => "btn btn-xs bg-orange"} %>
          <% end %>-->
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/purchase_bills/edit.html.erb
<div class="box box-success">
  <div class="box-header with-border">
    <h3 class="box-title"><%= t('helpers.title.purchase_bill.edit') %></h3>
  </div>
  <%= render 'form', :purchase_bill => @purchase_bill %>
</div>

app/views/purchase_bills/index.html.erb
<div class="box box-success">
  <div class="box-header with-border box-success">
    <h3 class="box-title"><%= t('helpers.title.purchase_bill.list') %></h3>
    <% if (can? :create, PurchaseBill) %>
      <%= link_to "<i class=\"fa fa-plus\"></i>".html_safe, new_purchase_bill_path, {:class => "btn btn-sm bg-green btn-title", :title => "Agregar Factura"} %>
    <% end %>
  </div>
  <div class="box-body">
    <div class="purchase_bill-search searchList">
      <%= search_form_for(@q, remote: true, :html => { class: 'remote-search' }) do |f| %>
        <div class="row">
          <div class="col-md-3">
            <div class="form-group has-feedback">
              <%= f.text_field :provider_name_or_provider_ruc_cont, class: 'form-control', autocomplete: 'off', placeholder: 'Busca por Nombre/RUC del proveedor' %>
              <i class="fa fa-search form-control-feedback"></i>
            </div>
          </div>
          <div class="col-md-3">
            <div class="btn btn-default daterange btn-block" id="date-range">
              <%= f.hidden_field :date_gteq, class: 'fecha-desde' %>
              <%= f.hidden_field :date_lteq, class: 'fecha-hasta' %>
              <i class="fa fa-calendar"></i>&nbsp;<span>Fecha</span>&nbsp;<b class="caret"></b>
            </div>
          </div>
          <div class="col-md-3">
            <%= f.select :condition_eq ,PurchaseBill.condition.options, {include_blank: 'Todas las condiciones...'}, class: 'form-control'%>
          </div>
          <div class="col-md-3">
            <%= f.select :state_eq ,PurchaseBill.state.options, {include_blank: 'Todos los estados...'}, class: 'form-control'%>
          </div>
        </div>
      <% end %>
    </div>
    <div class="overlay-wrapper searchResult table-responsive" id="purchase-bills-table">
      <%= render 'list', :purchase_bills => @purchase_bills %>
    </div>
  </div>
  <div class="box-footer clearfix">
    <div id="paginate-container">
      <ul class="pagination pagination-sm no-margin pull-right">
        <%= paginate @purchase_bills %>
      </ul>
    </div>
  </div>
</div>

app/views/purchase_bills/index.js.slim
| $("#purchase-bills-table").html("#{escape_javascript(render 'list', format: 'html', :purchase_bills => @purchase_bills)}");
| $('#paginate-container').html("#{escape_javascript(paginate(@purchase_bills, remote: true)) }");
| $('.searchResult > .overlay').remove();

app/views/purchase_bills/new.html.erb
<div class="box box-success">
  <div class="box-header with-border">
    <h3 class="box-title"><%= t('helpers.title.purchase_bill.new') %></h3>
  </div>
  <%= render 'form', :purchase_bill => @purchase_bill %>
</div>

app/views/purchase_bills/show.html.erb
<div class="box box-success">
  <div class="box-header">
    <h3 class="box-title">Factura Nro. <%= @purchase_bill.number %></h3>
  </div>
  <div class="box-body">
    <div class="row">
      <div class="field col-md-12 form-group">
        <div class="field col-md-3 form-group">
          <div class="field col-md-4">
            <strong>Fecha:</strong>
          </div>
          <div class="field col-md-8 show-padding">
            <%= @purchase_bill.date %>
          </div>
        </div>
        <div class="field col-md-4 form-group">
          <div class="field col-md-6">
            <strong>Condición de compra:</strong>
          </div>
          <div class="field col-md-5 show-padding">
            <%= @purchase_bill.condition %>
          </div>
        </div>
        <div class="field col-md-3 form-group">
          <div class="field col-md-4">
            <strong>Estado:</strong>
          </div>
          <div class="field col-md-8 show-padding">
            <label class="label label-<%= @purchase_bill.state.pagado? ? 'success' : 'warning' %>"><%= @purchase_bill.state_text %></label>
          </div>
        </div>
      </div>

      <div class="field col-md-12 form-group">
        <div class="field col-md-6 form-group">
          <div class="field col-md-2">
            <strong>Cliente:</strong>
          </div>
          <div class="field col-md-8 show-padding">
            <%= @purchase_bill.provider_name %>
          </div>
        </div>

      </div>

    </div>
    <br><br>
    <div class="row">
      <div class="col-md-12">
        <div class="nav-tabs-custom">
          <ul class="nav nav-tabs">
            <li class="active"><a href="#tab_1" data-toggle="tab">Materiales</a></li>
            <li><a href="#tab_2" data-toggle="tab">Pagos</a></li>
            <% if @purchase_bill.crédito? %>
                <li><a href="#tab_3" data-toggle="tab">Pagos Pendientes</a></li>
            <% end %>
          </ul>
          <div class="tab-content">
            <div class="tab-pane active" id="tab_1">
              <table class="table table-bordered table-condensed">
                <thead>
                <tr>
                  <th>Material</th>
                  <th>Unidad</th>
                  <th>Cantidad</th>
                  <th>Precio Unitario</th>
                  <th>Subtotal</th>
                </tr>
                </thead>
                <tbody>
                <% @purchase_bill.purchase_details.each do |d| %>
                    <tr>
                      <td><%= d.material.name %></td>
                      <td><%= d.material.measurement_unit %></td>
                      <td class="text-right"><%= d.quantity %></td>
                      <td class="text-right"><%= number_to_currency_py(d.price) %></td>
                      <td class="text-right"><%= number_to_currency_py(d.total) %></td>
                    </tr>
                <% end %>
                </tbody>
                <tfoot>
                <tr>
                  <td colspan="3" class="text-bold text-right">Total:</td>
                  <td class="text-bold text-right"><%= number_to_currency_py(@purchase_bill.total) %></td>
                </tr>
                </tfoot>
              </table>
            </div>
            <div class="tab-pane" id="tab_2">
              <table class="table table-bordered table-condensed">
                <thead>
                <tr>
                  <th>Fecha de Pago</th>
                  <th>Monto</th>
                </tr>
                </thead>
                <tbody>
                <% if @purchase_bill.payments.count == 0 %>
                    <tr>
                      <td colspan="2"><strong>No se registran pagos</strong></td>
                    </tr>
                <% end %>
                <% @purchase_bill.payments.each do |p| %>
                    <tr>
                      <td><%= p.date %></td>
                      <td><%= number_to_currency_py(p.amount) %></td>
                    </tr>
                <% end %>
                </tbody>
              </table>
            </div>
            <div class="tab-pane" id="tab_3">
              <table class="table table-bordered table-condensed">
                <thead>
                <tr>
                  <th>Vencimiento</th>
                  <th>Monto</th>
                  <th>Saldo</th>
                  <th>Pagar Gs.</th>
                </tr>
                </thead>
                <tbody>
                <% @purchase_bill.installment_purchases.each do |i| %>
                    <tr>
                      <td><%= i.due_date %></td>
                      <td class="text-right"><%= number_to_currency_py(i.amount) %></td>
                      <td class="text-right"><%= number_to_currency_py(i.balance) %></td>
                      <td>
                        <% if not i.balance == 0 %>
                            <% payment = InstallmentPaymentPurchase.new %>
                            <%= form_for payment, url: url_for(:controller => 'installment_payment_purchase', :action => 'create') do |f| %>
                                <%= f.hidden_field :installment_purchase_id, value: i.id %>
                                <div class="col-md-5">
                                  <div class="input-group">
                                    <%= f.text_field :amount, value: i.balance, class: "form-control input-sm maskMoneda" %>
                                    <span class="input-group-btn">
                                    <%= f.submit "Pagar", {:class => "btn btn-primary btn-sm"} %>
                                  </span>
                                  </div>
                                </div>
                            <% end %>
                        <% else %>
                            <p class="text-green">Pagado</p>
                        <% end %>
                      </td>
                    </tr>
                <% end %>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
    <% if @purchase_bill.pendiente? %>
        <div class="row">
          <div class="col-sm-offset-8 col-sm-4">
            <div class="box box-solid">
              <div class="box-body">
                <table class="table">
                  <tbody>
                  <tr class="bg-green">
                    <td class="text-bold">Total pagado:</td>
                    <td class="text-right text-bold"><%= number_to_currency_py(@purchase_bill.total - @purchase_bill.balance) %></td>
                  </tr>
                  <tr class="bg-red">
                    <td class="text-bold">Total pendiente:</td>
                    <td class="text-right text-bold"><%= number_to_currency_py(@purchase_bill.balance) %></td>
                  </tr>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
    <% end %>
  </div>
  <div class="box-footer">
    <div class="pull-right">
      <%= link_to "<i class=\"fa fa-arrow-left\"></i>".html_safe, url_for(:back), {:class => "btn btn-default", :title => "Atrás"} %>
    </div>
  </div>
</div>