config/routes.rb
Rails.application.routes.draw do
  resources :sale_bills, except: [:destroy, :update]
  resources :concepts
  resources :account_employees, except: [:destroy]
  resources :budgets do
    member do
      get :cancel
      get :deliver
      get :reject
      get :get_detail
    end
  end
  #resources :budgets
  get 'rubros/search' => 'rubros#search'
  resources :rubros
  resources :certifications, except: [:destroy] do
    member do
      get :rejected
      get :approved
    end
  end
  resources :client_certifications do
    member do
      get :get_detail
    end
  end
  get 'employees/search' => 'employees#search'
  resources :employees
  resources :purchase_bills
  get 'providers/search' => 'providers#search'
  resources :providers
  get 'services/search' => 'services#search'
  resources :services
  get 'contracts/search' => 'contracts#search'
  resources :contracts
  get 'clients/search' => 'clients#search'
  resources :clients
  get 'materials/search' => 'materials#search'
  resources :materials
  resources :movement_details
  resources :material_movements
  resources :roles, except: [:destroy]
  resources :permissions, only: [:create, :update, :destroy]
  resources :audit, only: [:index]
  resources :installment_payment
  resources :installment_payment_purchase
  root to: 'welcome#index'
  get 'welcome/index'
  get 'profile', to: 'users#edit_profile', as: 'edit_profile'
  post 'profile', to: 'users#update_profile', as: 'update_profile'
  devise_for :users
  resources :users
  get 'company_config', to: 'company_config#edit_company', as: 'edit_company'
  post 'company_config', to: 'company_config#update_company', as: 'update_company'
  resources :budgets do
    resources :budgets_details
  end
  get 'reports' , to: 'reports#index', as: :reports
  get 'reports/materials' , to: 'reports#materials', as: :reports_materials
  get 'reports/bills' , to: 'reports#bills', as: :reports_bills
  get 'reports/employees' , to: 'reports#employees', as: :report_employees

end

app/models/certification.rb
class Certification < ApplicationRecord
  audited
  belongs_to :contract
  has_many :certification_details

  enum state: { pending: 0, rejected: 1, approved: 2, paid: 3 }
  enum state_type: {Pendiente:0, Rechazado:1, Aprobado:2, Pagado:3 }
  delegate :name, to: :contract, prefix: true
  accepts_nested_attributes_for :certification_details, allow_destroy: true
  after_commit :update_balance

  scope :pay_current, -> { CompanyConfig.all.pluck(:current_pay).first }

  validates :contract_id, :presence => {:message => "Seleccione una obra"}
  validates :date, :presence => {:message => "Seleccione una fecha"}
  validates :state, :presence => {:message => "Seleccione un estado"}
  validate :is_empty_detail

  def is_empty_detail
    if certification_details.empty?
      errors.add(:certification_details, "Debe agregar al menos un detalle")
    end
  end

  def update_balance
    aproved_certification = Certification.find(id)
    if(aproved_certification.approved?)
      account = AccountEmployee.where(contract_id: aproved_certification.contract_id)

      if(account.blank?)
        #crea movimiento en cta. cte. empleado
        AccountEmployee.transaction do
          begin
            new_account = AccountEmployee.new(contract_id: aproved_certification.contract_id, date: Time.now)
            if new_account.save
              certification_details.each do |d|
                new_account_detail = AccountEmployeeDetail.new(account_employee_id: new_account.id, certification_id: aproved_certification.id, employee_id: d.employee_id, total: d.total, state: "Pendiente", date:Date.today)
                if new_account_detail.save
                  #actualiza saldo empleado
                  before_balance = Employee.find(d.employee_id).balance
                  Employee.find(d.employee_id).update_attribute(:balance, before_balance + d.total)
                end
              end
            end
            true
          rescue => e
            false
          end
        end
      else

        puts(certification_details)
        certification_details.each do |d|
          new_account_detail = AccountEmployeeDetail.new(account_employee_id: account.pluck(:id).first, certification_id: aproved_certification.id, employee_id: d.employee_id, total: d.total,state:"Pendiente", date:Date.today)
          if new_account_detail.save
            #actualiza saldo empleado
            before_balance = Employee.find(d.employee_id).balance
            Employee.find(d.employee_id).update_attribute(:balance, before_balance + d.total)
          end
        end

      end

    end
  end

end

app/controllers/certifications_controller.rb
class CertificationsController < ApplicationController
  add_breadcrumb I18n.t('helpers.breadcrumbs.certifications.index'), :certifications_path
  before_action :set_certification, only: [:show, :edit, :update]
  before_action :load_permissions
  authorize_resource

  def index
    get_certifications
  end

  def rejected
    certification = Certification.find(params[:id])
    if certification.pending?
      certification.rejected!
      redirect_to certification_url(certification), flash: {notice: 'La certificación interna ha sido rechazada'}
    end
  end

  def approved
    certification = Certification.find(params[:id])
    if certification.pending?
      certification.approved!
      redirect_to certification_url(certification), flash: {notice: 'La certificación interna ha sido aprobada'}
    end
  end

  def new
    add_breadcrumb I18n.t('helpers.breadcrumbs.certifications.new')
    @certification = Certification.new
    @certification.date = Time.now
    @certification.contract_id = params[:contract_id]
  end

  def show
    add_breadcrumb I18n.t('helpers.breadcrumbs.certifications.show')
    @certification = Certification.find(params[:id])
    @certification_details = CertificationDetail.find(@certification.id)
    respond_to do |format|
      format.html
      format.json {render json: @certification, include: :certification_details}
    end
  end

  def edit
    add_breadcrumb I18n.t('helpers.breadcrumbs.certifications.edit')
  end

  def create
    @certification = Certification.new(certification_params)
    respond_to do |format|
      if @certification.save
        format.html { redirect_to @certification.contract, notice: 'Certificación interna se creó correctamente' }
        format.json { render :show, status: :created, location: @certification }
      else
        format.html { render :new }
        format.json { render json: @certification.errors, status: :unprocessable_entity }
      end
    end
  end



  def update
    respond_to do |format|
      if @certification.update(certification_params)
        format.html { redirect_to @certification.contract, notice: 'Certificación interna se actualizó correctamente.' }
        format.json { render :show, status: :ok, location: @certification }
      else
        format.html { render :edit }
        format.json { render json: @certification.errors, status: :unprocessable_entity }
      end
    end
  end

  private
  def get_certifications
    @q = Certification.ransack(params[:q])
    @q.sorts = ['date desc', 'state asc','contract_name asc'] if @q.sorts.empty?
    @certifications = @q.result.page(params[:page])
  end
  def set_certification
    @certification = Certification.find(params[:id])
  end

  def certification_params
    params.require(:certification).permit(:contract_id, :date, :state, :certification_details_attributes => [:id, :employee_id, :quantity, :pay, :discount, :observation, :subtotal, :total, :_destroy])
  end
end

app/views/certifications/_form.erb
<%= nested_form_for certification, validate: true, :html => { class: 'form-horizontal' } do |f| %>

    <div class="box-body box-success">
      <div class="field col-md-12 form-group">
        <div class="field col-md-6 form-group">
          <div class="col-md-2">
            <%= f.label :contract, 'Contrato:', :class => 'control-label  tooltip_required' %>
          </div>
          <div class="col-md-8">
            <%= f.collection_select(:contract_id, Contract.all, :id, :name, {prompt: 'Selecciona un contrato'}, :class => 'select-two form-control') %>
          </div>
        </div>
        <div class="field col-md-6 form-group">
          <div class="col-md-3">
            <%= f.label :date, 'Fecha:', :class => 'control-label tooltip_required' %>
          </div>
          <div class="input-group col-md-7">
            <%= f.text_field :date, :id => 'datepickerFrom', :class => 'input-group date form-control datepicker', :value => Date.today %>
            <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
          </div>
        </div>
      </div>

      <div class="col-md-12">
        <div class="box box-success">
          <div class="box-body">
              <table class="table table-bordered table-condensed">
                <thead>
                <tr>
                  <th width="18%">Jornalero</th>
                  <th width="9%">Días trabajados</th>
                  <th width="9%">Jornal</th>
                  <th width="9%">Descuento</th>
                  <th>Observacion</th>
                  <th width="9%">Subtotal</th>
                  <th width="3%"></th>
                </tr>
                </thead>
                <tbody>
                <%= f.fields_for :certification_details, :wrapper => false do |certification| %>
                    <tr class="fields ">
                      <td><%=certification.collection_select(:employee_id, Employee.all, :id, :name, {prompt: 'Selecciona un Jornalero'}, class: 'form-control')%></td>
                      <td><%=certification.number_field :quantity, class: 'form-control', min:0 %></td>
                      <td><%=certification.number_field :pay, class: 'form-control', min:0 %></td>
                      <td><%=certification.number_field :discount, class: 'form-control', min:0 %></td>
                      <td><%=certification.text_area :observation, class: 'form-control'%></td>
                      <td><%=certification.number_field :subtotal, class: 'form-control', disabled:true %></td>
                      <td><%=certification.link_to_remove '<i class="fa  fa-trash-o"></i>'.html_safe, class: 'btn btn-danger'%></td>
                      <br>
                    </tr>
                <% end %>
                <td>
                  <%=f.link_to_add '<i class="fa fa-plus"></i>'.html_safe, :certification_details, class: ' insert_in_table btn btn-flat bg-green'%>
                </td>
                </tbody>
              </table>
          </div>
        </div>
      </div>
    </div>

    <div class="box-footer">
      <div class="pull-right">
        <%= f.submit 'Guardar', :class => 'btn btn-primary' %>
        <%= link_to 'Cancelar', certifications_path, :class => 'btn btn-default' %>
      </div>
    </div>
<% end %>


  <script type="text/javascript">
    $(document).ready(function() {
      $(".select-two").select2({
        language:'es'
      });
    });
  </script>

app/views/certifications/_form.html.erb
<%= nested_form_for certification, validate: true, :html => { class: 'form-horizontal' } do |f| %>

    <div class="box-body box-success">
      <div class="field col-md-12 form-group">
        <div class="field col-md-6 form-group">
          <div class="col-md-2">
            <%= f.label :contract, 'Contrato:', :class => 'control-label  tooltip_required' %>
          </div>
          <div class="col-md-8">
            <%= f.collection_select(:contract_id, Contract.all, :id, :name, {prompt: 'Selecciona un contrato'}, :class => 'form-control', disabled:true) %>
            <%= f.hidden_field :contract_id, :class => 'form-control' %>
          </div>
        </div>
        <div class="field col-md-6 form-group">
          <div class="col-md-3">
            <%= f.label :date, 'Fecha:', :class => 'control-label tooltip_required', disabled:true %>

          </div>
          <div class="input-group col-md-7">
            <%= f.text_field :date, :id => 'datepickerFrom', :class => 'input-group date form-control datepicker', disabled:true%>
            <%= f.hidden_field :date, :class => 'form-control' %>
            <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
          </div>
        </div>
      </div>
      <div class="col-md-12">
        <div class="box box-success">
          <div class="box-body">
              <table class="table table-bordered table-condensed" id="certification-table">
                <thead>
                <tr>
                  <th width="18%">Jornalero</th>
                  <th width="9%">Días trabajados</th>
                  <th width="9%">Jornal(Gs)</th>
                  <th width="9%">Descuento(%)</th>
                  <th>Observación</th>
                  <th width="9%">Subtotal(Gs)</th>
                  <th width="9%">Total(Gs)</th>
                  <th width="3%"></th>
                </tr>
                </thead>
                <tbody id="details-body">
                <%= f.fields_for :certification_details, :wrapper => false do |certification| %>
                    <tr class="fields" onchange='getCertificationTotal(this,"<%= Certification.pay_current %>");'>
                      <td>
                        <%= certification.collection_select :employee_id, Employee.all, :id, :name_with_initial, {prompt: 'Buscar Jornalero'}, {class: "form-control select2 people-search"} %>
                      </td>
                      <td><%=certification.number_field :quantity, class: 'form-control quantity numeric', min:0, max:365, id:'quantity' %></td>
                      <td><%=certification.number_field :pay, class: 'form-control pay', min:0, max:9999999999 %></td>
                      <td><%=certification.number_field :discount, class: 'form-control discount', min:0, max:100, id:'discount' %></td>
                      <td><%=certification.text_area :observation, class: 'form-control', maxlength: 200 %></td>
                      <td><%=certification.number_field :subtotal, class: 'form-control subtotal', readonly:true%></td>
                      <td><%=certification.number_field :total, class: 'form-control total', readonly:true%></td>
                      <td><%=certification.link_to_remove '<i class="fa  fa-trash-o"></i>'.html_safe, class: 'btn btn-danger' %></td>
                      <br>
                    </tr>
                <% end %>
                <td>
                  <%=f.link_to_add '<i class="fa fa-plus"></i>'.html_safe, :certification_details, class: ' insert_in_table btn bg-green'%>
                </td>
                </tbody>
              </table>
          </div>
        </div>
      </div>
    </div>

    <div class="box-footer">
      <div class="pull-right">
        <button type="submit" class="btn btn-primary"><i class="fa fa-save"></i></button>
        <%= link_to "<i class=\"fa fa-arrow-left\"></i>".html_safe, certification.contract, :class => 'btn btn-default' %>
      </div>
    </div>
<% end %>

<script type="text/javascript">
  Certification.setSearchEmployee('<%= employees_search_path %>');
</script>

app/views/certifications/_list.erb
<table class="table table-bordered table-condensed">
  <thead>
  <tr>
    <th>Contrato</th>
    <th>Fecha</th>
    <th class="table-actions"></th>
  </tr>
  </thead>

  <tbody>
  <% certifications.each do |certification| %>
      <tr>
        <td><%= certification.contract_name %></td>
        <td><%= certification.date %></td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/certifications/_list.html.erb
<table class="table table-bordered table-condensed table-list">
  <thead>
  <tr>
    <th width="10%">N° de certificación</th>
    <th width="30%">Contrato</th>
    <th width="10%">Fecha</th>
    <th width="5%">Estado</th>
    <th width="10%" class="table-actions"></th>
  </tr>
  </thead>

  <tbody>
  <% certifications.each do |certification| %>
      <tr>
        <td><%= certification.certification_number %></td>
        <td><%= certification.contract_name %></td>
        <td><%= certification.date %></td>
        <td>
        <% if certification.approved?%>
            <span class="label label-success">Aprobado</span>
        <%elsif certification.pending? %>
            <span class="label label-warning">Pendiente</span>
        <%elsif certification.rejected? %>
            <span class="label label-danger">Rechazado</span>
        <% elsif certification.paid?%>
            <span  class="label label-default">Pagado</span>
        <% end %>
        </td>
        <td>
          <%= link_to "<i class=\"fa fa-eye\"></i>".html_safe, certification_path(certification), {:class => 'btn btn-xs bg-teal', :title=> 'Ver'} %>

          <% if (can? :update, Certification) && certification.pending? %>
              <%= link_to "<i class=\"fa fa-pencil\"></i>".html_safe, edit_certification_path(certification), :class => 'btn btn-xs bg-orange',:title => 'Editar'%>
              <%= link_to "<i class=\"fa fa-check\"></i>".html_safe, approved_certification_path(certification), :class => 'btn btn-xs  bg-green', :title => 'Aprobar',data: {confirm: 'La certificación interna fué aprobada?'}  %>
              <%= link_to "<i class=\"fa fa-times\"></i>".html_safe, rejected_certification_path(certification), :class => 'btn btn-xs bg-red', :title => 'Rechazar',data: {confirm: 'La certificación interna fué rechazada?'} %>
          <% end %>

        </td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/certifications/edit.erb
<div class="box box-success">
  <div class="box-header with-border">
    <h3 class="box-title"><%= t('helpers.title.certification.edit') %></h3>
  </div>
  <%= render 'form', :certification => @certification %>
</div>

app/views/certifications/edit.html.erb
<div class="box box-success">
  <div class="box-header with-border">
    <h3 class="box-title"><%= t('helpers.title.certification.edit') %></h3>
  </div>
  <%= render 'form', :certification => @certification %>
</div>

app/views/certifications/index.erb
<div class="box box-success">
  <div class="box-header with-border box-success">
    <h3 class="box-title"><%= t('helpers.title.certification.list') %></h3>
    <%= link_to "<i class=\"fa fa-plus\"></i>".html_safe, new_certification_path, {:class => "btn btn-sm btn-flat bg-green btn-title", :title => "Agregar Certificación"} %>
  </div>
  <div class="box-body">
    <div class="certification-search searchList">
      <%= search_form_for(@q, remote: true, :html => { class: 'remote-search' }) do |f| %>
          <div class="input-group">
            <%= f.text_field :contract_name, class: 'form-control', autocomplete: 'off', placeholder: 'Busca por obra' %>
            <div class="input-group-btn">
              <button type="submit" name="button" class="btn btn-default">
                <i class="fa fa-search"></i>
              </button>
            </div>
          </div>
      <% end %>
    </div>
    <div class="overlay-wrapper searchResult table-responsive" id="certifications-table">
      <%= render 'list', :certifications => @certifications %>
    </div>
  </div>
  <div class="box-footer clearfix">
    <div id="paginate-container">
      <ul class="pagination pagination-sm no-margin pull-right">
        <%= paginate @certifications %>
      </ul>
    </div>
  </div>
</div>

app/views/certifications/index.html.erb
<div class="box box-success">
  <div class="box-header with-border box-success">
    <h3 class="box-title"><%= t('helpers.title.certification.list') %></h3>
  </div>
  <div class="box-body">
    <div class="certification-search searchList">
      <%= search_form_for(@q, remote: true, :html => { class: 'remote-search' }) do |f| %>
          <div class="row">
            <div class="col-md-4">
              <div class="form-group has-feedback">
                <%= f.text_field :contract_name_cont, class: 'form-control', autocomplete: 'off', placeholder: 'Busca por Contrato' %>
                <i class="fa fa-search form-control-feedback"></i>
              </div>
            </div>
            <div class="col-md-4">
              <div class="btn btn-default daterange btn-block" id="date-range">
                <%= f.hidden_field :date_gteq, class: 'fecha-desde' %>
                <%= f.hidden_field :date_lteq, class: 'fecha-hasta' %>
                <i class="fa fa-calendar"></i>&nbsp;<span>Fecha</span>&nbsp;<b class="caret"></b>
              </div>
            </div>
            <div class="col-md-4">
              <%= f.select :state_eq ,Certification.state_types, {include_blank: 'Todos los estados...'}, class: 'form-control'%>
            </div>
          </div>
      <% end %>
    </div>
    <div class="overlay-wrapper searchResult table-responsive" id="certifications-table">
      <%= render 'list', :certifications => @certifications %>
    </div>
  </div>
  <div class="box-footer clearfix">
    <div id="paginate-container">
      <ul class="pagination pagination-sm no-margin pull-right">
        <%= paginate @certifications %>
      </ul>
    </div>
  </div>
</div>

app/views/certifications/index.js.slim
| $("#certifications-table").html("#{escape_javascript(render 'list', format: 'html', :certifications => @certifications)}");
| $('#paginate-container').html("#{escape_javascript(paginate(@certifications, remote: true)) }");
| $('.searchResult > .overlay').remove();

app/views/certifications/new.erb
<div class="box box-success">
  <div class="box-header with-border">
    <h3 class="box-title"><%= t('helpers.title.certification.new') %></h3>
  </div>
  <%= render 'form', :certification => @certification %>
</div>

app/views/certifications/new.html.erb
<div class="box box-success">
  <div class="box-header with-border">
    <h3 class="box-title"><%= t('helpers.title.certification.new') %></h3>
  </div>
  <%= render 'form', :certification => @certification %>
</div>

app/views/certifications/show.html.erb
<div class="box box-success">
  <div class="box-header with-border">
    <h3 class="box-title"><%= t('helpers.title.certification.show') %></h3>
  </div>
  <div class="box-body">

    <div class="field col-md-12 form-group">
      <div class="field col-md-6 form-group">
        <div class="col-md-6 show-padding">
          <strong>Obra:</strong>
          <%= @certification.contract_name %>
        </div>
      </div>

      <div class="field col-md-6 form-group">
        <div class="col-md-6 show-padding">
          <strong>Fecha:</strong>
          <%= @certification.date %>
        </div>
      </div>
    </div>
    <div class="field col-md-12 form-group">
      <div class="field col-md-6 form-group">
        <div class="col-md-6 show-padding">
          <strong>N° de  certificación:</strong>
          <%= @certification.certification_number %>
        </div>
      </div>
      <div class="field col-md-6 form-group">
        <div class="col-md-6 show-padding">
          <strong>Estado:</strong>
          <% if @certification.approved?%>
              <label class="label label-success">Aprobado</label>
          <%elsif @certification.pending? %>
              <label class="label label-warning">Pendiente</label>
          <%elsif @certification.rejected? %>
              <label class="label label-danger">Rechazado</label>
          <% elsif @certification.paid?%>
              <label  class="label label-default">Pagado</label>
          <% end %>
        </div>
      </div>
    </div>

    <div class="col-md-12 form-group">
      <table class="table table-bordered table-condensed table-list">
        <thead>
        <tr  style="word-wrap: break-word">
          <th width="20%">Jornalero</th>
          <th width="10%">Días trabajados</th>
          <th width="10%">Jornal</th>
          <th width="10%">Descuento(%)</th>
          <th width="30%">Observación</th>
          <th width="10%">Subtotal</th>
          <th width="10%">Total</th>
        </tr>
        </thead>
        <tbody>
        <% @certification.certification_details.each do |detail| %>
            <tr>
              <td><%= detail.employee_name %>&nbsp;<%= detail.employee_last_name %>
              <td><%= detail.quantity %>
              <td><%= number_to_currency_py(detail.pay) %>
              <td><%= eval(sprintf("%3.2f",detail.discount)) %>
              <td><%= detail.observation%>
              <td><%= number_to_currency_py(detail.subtotal) %></td>
              <td><%= number_to_currency_py(detail.total) %>
            </tr>
        <% end %>
        </tbody>
      </table>
    </div>

  </div>
  <div class="box-footer">
    <div class="pull-right">
      <% if (can? :update, Certification) && @certification.pending? %>
          <%= link_to "<i class=\"fa fa-pencil\"></i>".html_safe, edit_certification_path(@certification), :class => 'btn bg-orange', :title => 'Editar'%>
          <%= link_to "<i class=\"fa fa-check\"></i>".html_safe, approved_certification_path(@certification), :class => 'btn bg-green', :title => 'Aprobar', data: {confirm: 'La certificación interna fué aprobada?'} %>
          <%= link_to "<i class=\"fa fa-times\"></i>".html_safe, rejected_certification_path(@certification), :class => 'btn bg-red', :title => 'Rechazar', data: {confirm: 'La certificación interna fué rechazada?'} %>
      <% end %>
      <%= link_to "<i class=\"fa fa-arrow-left\"></i>".html_safe, @certification.contract, :class => 'btn btn-default', :title => 'Atrás' %>
    </div>
  </div>
</div>